### ISSUE TITLE
Cannot access recently published 3rd party module when Accept header isn't present

### ISSUE THREAD

**Issue by JamesBroadberry** [denoland/deno_website2#388]
Hi,

I've recently submitted my module as PR #383 to the database.json file.
On the website, this looks fine and is available here: https://deno.land/x/bcrypt/mod.ts

However, when trying to import the code (or sending a GET request leaving the Accept header off with Postman) at the same URL, I get a 404 with message: "Not in database.json /x/bcrypt/mod.ts"

Here is the stack trace when trying to run the file, in case it's needed:

`PS C:\Users\James\Documents\Code\ConsumeBCrypt-Deno> deno run .\index.ts --reload
Compile file:///C:/Users/James/Documents/Code/ConsumeBCrypt-Deno/index.ts
Download https://deno.land/x/bcrypt/mod.ts
error: Uncaught Error: Import 'https://deno.land/x/bcrypt/mod.ts' failed: 404 Not Found
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async processImports ($deno$/compiler/imports.ts:117:23)
    at async Object.processImports ($deno$/compiler/imports.ts:125:7)
    at async compile (file:///D:/a/deno/deno/cli/js/compiler.ts:144:31)
    at async tsCompilerOnMessage (file:///D:/a/deno/deno/cli/js/compiler.ts:359:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)`

If I just need to wait some time for the changes to propogate, that's fine!

Thanks,
James

**Comment by JamesBroadberry** [comment]
I've looked through the code which handles the requests and stepped through the handleRequest function in worker/index.js manually.
 
Seems to resolve find and return fetch("https://raw.githubusercontent.com/jamesbroadberry/deno-bcrypt/master/mod.ts") which is correct. 

Sounds like a CI thing but I'm not familiar with all of this so think this as far as I can go, sorry!

**Comment by JamesBroadberry** [comment]
Looks like this is due to the [CI failing](https://github.com/denoland/deno_website2/runs/663130137).

Not sure if it's the solution but bumping the version of the Cloudflare wrangler action might solve it?

**Comment by JamesBroadberry** [comment]
Looks like this was fixed as part of #393 
Thanks @ry
